[tool.poetry]
name = "mario"
version = "0.1.0"
description = "The CITS3001 project with the Super Mario Bros simulation."
authors = ["reilly-23615971 <23615971@student.uwa.edu.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gym-super-mario-bros = "^7.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
